name: test-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytest>=7.0
  - pytest-cov>=4.0
  - numpy>=1.24
  - pandas>=2.0
  - faiss-cpu>=1.7
  - pytorch::pytorch>=2.0
  - pytorch::torchvision
  - transformers>=4.30
  - spacy>=3.7
  - arxiv>=2.0
  - beautifulsoup4>=4.12
  - huggingface_hub>=0.19
  - pyyaml>=6.0
  - requests>=2.31
  - tqdm>=4.65
  - tenacity>=8.0
  - pydantic>=2.0
  - python-dateutil>=2.8
  - pip:
    - pytest-mock>=3.10