name: Run Pytest with Conda

on:
  push:
    branches:
      - '**'  # This will run on all branches
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test-env
          environment-file: .github/workflows/ci-environment.yaml
          auto-activate-base: false

      - name: Install Package in Editable Mode
        run: pip install -e .
        
      - name: Install Ghostscript
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript

      - name: Run Pytest
        shell: bash -l {0}
        run: |
          pytest tests/ --junitxml=test-results.xml --cov=local_llm_researcher --cov-report=xml

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: test-results.xml
